config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :goals do
    patch 'update_status', on: :member
    resources :sub_goals do
      patch 'update_status', on: :member
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :goal_categories
  has_many :goals, through: :goal_categories
end

app/models/frequency.rb
class Frequency < ApplicationRecord
  has_many :goals
end

app/models/goal.rb
class Goal < ApplicationRecord
  has_many :goal_categories
  has_many :categories, through: :goal_categories
  accepts_nested_attributes_for :goal_categories, :categories
  has_many :sub_goals
  has_many :goal_occurences
  belongs_to :frequency, optional: true

  COLORS = ["#FCEBD4", "#FFF8D3"]
end

app/models/goal_category.rb
class GoalCategory < ApplicationRecord
  belongs_to :goal
  belongs_to :category
end

app/models/goal_occurence.rb
class GoalOccurence < ApplicationRecord
  belongs_to :goal
end

app/models/sub_goal.rb
class SubGoal < ApplicationRecord
  belongs_to :goal
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @goals = Goal.where(frequency_id: nil)
    if params[:date]
      @goals = Goal.left_outer_joins(:sub_goals)
                   .where("goals.end_date = ? OR sub_goals.end_date = ?", params[:date], params[:date])
    end
    @goal_events = Goal.where.not(end_date: nil)
    @sub_goal_events = SubGoal.where.not(end_date: nil)

    @habits = Goal.where.not(frequency_id: nil)
    respond_to do |format|
      format.html
      format.text { render partial: "goals/goals", locals: { goals: @goals }, formats: [:html] }
    end
  end

  def new
    @goal = Goal.new(categories: [Category.new])
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.frequency_id = Frequency.find(params[:goal][:frequency_id].to_i).id if params[:goal][:frequency_id] != ""
    @goal.start_date = Date.today
    @goal.status = "in progress"
    determine_categories

    if @goal.save
      redirect_to goals_path
    else
      render 'new'
    end
  end

  def update_status
    @goal = Goal.find(params[:id])
    @goal.update(status: 'completed')

    head :no_content
  end

  private

  def goal_params
    params.require(:goal).permit(:end_date, :name, :occurence)
  end

  def determine_categories
    if params[:goal][:categories_attributes]
      params[:goal][:categories_attributes].each do |_key, cat_attr|
        if cat_attr[:name] != [] && cat_attr[:id] == ""
          category = Category.find(cat_attr[:id].to_i)
          create_goal_category(category, cat_attr)
        elsif cat_attr[:name] == [] && cat_attr[:id] != ""
          create_category(cat_attr)
        end
      end
    end
  end

  def create_category(cat_attr)
    category = Category.create(
      name: cat_attr[:name],
      score: 0
    )
    create_goal_category(category, cat_attr)
  end

  def create_goal_category(category, cat_attr)
    GoalCategory.create(
      category_id: category.id,
      goal_id: @goal.id,
      score: cat_attr[:goal_category][:score]
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/sub_goals_controller.rb
class SubGoalsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def update_status
    @sub_goal = SubGoal.find(params[:id])
    @sub_goal.update(status: 'completed')

    head :no_content
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/goals/_category.html.erb
<%= f.fields_for :category do |category| %>
  <%= f.input :id, collection: Category.all + [Category.new(name: "Custom")], include_blank: true, label: false %>
  <%= f.input :name, label: false %>
  <%= f.fields_for :goal_category do |category| %>
    <%= category.input :score, as: :integer, label: false %>
  <% end %>
<% end %>

app/views/goals/_form.html.erb
<%= simple_form_for(@goal) do |f| %>
  <%= f.input :name %>
  <%= f.input :end_date, as: :date, html5: true %>
  <%= f.input :occurence, as: :integer %>
  <%= f.association :frequency %>
  <div class="category-fields" data-controller="category">
    <%= f.fields_for :categories do |category| %>
      <div data-category-target="field">
        <%= render "category", f: category %>
      </div>
      <%= button_tag "Add another category", type: "button", class: "secondary-btn bg-white", data: { action: "click->category#add" } %>
    <% end %>
  </div>
  <%= f.submit "Create my goal", class: "primary-btn" %>
<% end %>

app/views/goals/_goals.html.erb
<div class="col-12 col-lg-7" data-calendar-target="goals">
  <% goals.each do |goal| %>
    <div style="background-color: <%= Goal::COLORS[goal.id % Goal::COLORS.length] %>;" class="goal-item">
      <% if !goal.occurence.nil?%>
        <div class="goal-item-date">
          <div class="rotate-goal">
            <i class="fa-solid fa-rotate"></i>
          </div>
        </div>
      <% else %>
        <div class="goal-item-date">
          <p class="week-day-date"><%= goal.end_date.strftime("%^a") %></p>
          <p class="day-date"><%= goal.end_date.strftime("%-d") %></p>
        </div>
      <% end %>
      <div class="goal-options">
        <%= link_to '<i class="fa-solid fa-plus"></i>'.html_safe, new_goal_sub_goal_path(goal) %>
        <%= link_to '<i class="fa-solid fa-wand-magic"></i>'.html_safe, edit_goal_path(goal) %>
      </div>
      <div class="goal-item-name">
        <p class="goal-name"><%= goal.name %></p>
      </div>
      <div class="goal-categories">
        <% goal.goal_categories.each do |goal_category| %>
          <div class="goal-category">
            <p class="gc-score"> + <%= goal_category.score %></p>
            <p><%= goal_category.category.name %></p>
          </div>
        <% end %>
      </div>
      <% if goal.status != "completed" %>
        <div data-goal-id="<%= goal.id %>">
          <div class="progress" id="spinner" data-action="click->checkmark#check">
            <i class="fa-solid fa-spinner"></i>
          </div>
          <div id="check-mark" data-checkmark-target="checkmark" class="progress d-none" >
            <i class="fa-solid fa-check"></i>
          </div>
        </div>
      <% else %>
        <div class="progress" >
          <i class="fa-solid fa-check"></i>
        </div>
      <% end %>
    </div>
    <% if !goal.sub_goals.empty? %>
      <div class="sub-goals">
        <% goal.sub_goals.each do |sub_goal| %>
          <div style="background-color: #D8F5D9;" class="goal-item sub-goal-item">
            <% if !goal.occurence.nil?%>
              <div class="goal-item-date">
                <div class="rotate-goal">
                  <i class="fa-solid fa-rotate"></i>
                </div>
              </div>
            <% else %>
              <div class="goal-item-date sub-goal-date">
                <p class="week-day-date"><%= sub_goal.end_date.strftime("%^a") %></p>
                <p class="day-date sub-day-date"><%= sub_goal.end_date.strftime("%-d") %></p>
              </div>
            <% end %>
            <div class="goal-item-name sub-goal-name">
              <p class="goal-name"><%= sub_goal.name %></p>
            </div>
            <% if sub_goal.status != "completed" %>
              <div data-sub-goal-id="<%= sub_goal.id %>" data-parent-id="<%= goal.id %>">
                <div class="progress sub-progress" id="spinner" data-action="click->checkmark#check">
                  <i class="fa-solid fa-spinner"></i>
                </div>
                <div id="check-mark" data-checkmark-target="checkmark" class="progress sub-progress d-none" >
                  <i class="fa-solid fa-check"></i>
                </div>
              </div>
            <% else %>
              <div class="progress sub-progress">
                <i class="fa-solid fa-check"></i>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  <% end %>
  <div>
    <p>Your recurring habits:</p>
    <% @habits.each do |goal| %>
      <div style="background-color: <%= Goal::COLORS[goal.id % Goal::COLORS.length] %>;" class="goal-item">
        <div class="goal-item-date">
          <div class="rotate-goal">
            <i class="fa-solid fa-rotate"></i>
          </div>
        </div>
        <div class="goal-options">
          <%= link_to '<i class="fa-solid fa-plus"></i>'.html_safe, new_goal_sub_goal_path(goal) %>
          <%= link_to '<i class="fa-solid fa-wand-magic"></i>'.html_safe, edit_goal_path(goal) %>
        </div>
        <div class="goal-item-name">
          <p class="goal-name"><%= goal.name %></p>
        </div>
        <div class="goal-categories">
          <% goal.goal_categories.each do |goal_category| %>
            <div class="goal-category">
              <p class="gc-score"> + <%= goal_category.score %></p>
              <p><%= goal_category.category.name %></p>
            </div>
          <% end %>
        </div>
        <% if goal.status != "completed" %>
          <div data-goal-id="<%= goal.id %>">
            <div class="progress" id="spinner" data-action="click->checkmark#check">
              <i class="fa-solid fa-spinner"></i>
            </div>
            <div id="check-mark" data-checkmark-target="checkmark" class="progress d-none" >
              <i class="fa-solid fa-check"></i>
            </div>
          </div>
        <% else %>
          <div class="progress" >
            <i class="fa-solid fa-check"></i>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/goals/index.html.erb
<div class="container" data-controller="calendar">
  <div class="row goals-container" data-controller="checkmark">
    <%= render 'goals', goals: @goals %>
    <div class="col-12 col-lg-5">
      <div class="sticky-calendar">
        <%= month_calendar(events: @goal_events, attribute: :start_date) do |date, goals| %>
          <% day_events = @goal_events.where(end_date: date) %>
          <% sub_day_events = @sub_goal_events.where(end_date: date) %>
          <div class="calendar-day <%= "day-marked" if day_events != [] || sub_day_events != [] %>" data-full-date="<%= date %>" data-calendar-target="day" data-action="click->calendar#load"><%= date.day %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/goals/new.html.erb
<div class="container">
  <div class="row justify-content-center my-5">
    <div class="col-12 col-lg-6">
      <h2 class="form-header">Add a new goal</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ontrack</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-bottom sticky-top bg-white">
  <div class="container my-navbar">
    <%= link_to goals_path do %>
      <%= image_tag "logo.png" %>
    <% end %>
    <% if user_signed_in? %>
      <div>
        <%= link_to "+ Add Goal", new_goal_path, class: "text-decoration-none primary-btn" %>
        <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "text-decoration-none secondary-btn" %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_old_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to goals_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading d-flex justify-center">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading d-flex align-items-center justify-content-center my-4">
    <%= link_to '<i class="fa-solid fa-chevron-left"></i>'.html_safe, calendar.url_for_previous_view %>
    <span class="calendar-title mx-5 mb-1"><%= t('date.month_names')[start_date.month].upcase %></span>
    <%= link_to '<i class="fa-solid fa-chevron-right"></i>'.html_safe, calendar.url_for_next_view %>
  </div>

  <table class="table border-0">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday][0] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>